### ISSUE TITLE
the flow_discharge  displayed below the sea?

### ISSUE THREAD

**Issue by tyszwh** [badlands-model/pyBadlands_serial#7]
In the previous version, the flow discharge that below the sea level should have not to be displayed in the results of flow network or tinsurface. But, now the results display the flow discharge in the entire model domain. Where should I find the problem?

Moreover, In the buildFlux.py, from buildMesh import _get_reference_elevation should change to from .buildMesh import _get_reference_elevation
the "self.input.erolays >= 0" need to be modifed for python3

**Comment by tristan-salles** [comment]
This is not an error we now display the flow above and under water in order to show submarine sediment laden gravity currents.
